### ISSUE TITLE
Debug node doesn't find page-view event

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi#349]
```
`ValueError('There is no event with type `page-view`. Check configuration for correct event type.'). Check run method of `DebugPayloadAction`

Details: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tracardi/service/wf/domain/execution_graph.py", line 207, in run_task
    result = await task
  File "/usr/local/lib/python3.8/site-packages/tracardi/process_engine/action/v1/debug_payload_action.py", line 120, in run
    raise ValueError(
ValueError: There is no event with type `page-view`. Check configuration for correct event type.`
```

**Comment by atompie** [comment]
@bceyssens Can you give more info on this bug. I guess it is not the space in the name we discussed lately?

**Comment by atompie** [comment]
Could not confirm. Latest tests show that it is working
