### ISSUE TITLE
Error under heavy load.

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#471]
```
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
    raise exceptions[0]
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/home/risto/PycharmProjects/tracardi-api/venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
```

**Comment by atompie** [comment]
https://github.com/tiangolo/fastapi/issues/4041
