### ISSUE TITLE
Create plugin that concatentates string

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#727]
**Is your feature request related to a problem? Please describe.**
Plugin that concatenates referenced strings in plugin config. This plugin is very simple in terms of python. The challenge is to add it as plugin. This is also very simple if you read this http://docs.tracardi.com/plugins/tutorial/part1/

**Describe the solution you'd like**
User defines in plugin configuration what strings he would like to concatenate. 

Example of configuration 

```json
{
   "strings": ["event@properties.emails", "my-string", ...]
}
```

Input:
Workflow payload

Output:
Concatenated string,

**Additional context**
To understand how the plugins work please read http://docs.tracardi.com/plugins/tutorial/part1/. It explains how to write plugins for Tracardi.

**Comment by riccardobucco** [comment]
Can I work on this issue?

**Comment by khadeom** [comment]
Hi i did not comment on this issue as it was self assigned by Mefpef, now could you assign me this issue?

**Comment by atompie** [comment]
@khadeom Done

**Comment by khadeom** [comment]
Thanks, atompie
I'm facing an issue while setting up the Python development environment while following the setup tutorial https://docs.tracardi.com/development/python_env/ 
I have python3.8.0 installed 
Please find the error below
```
(venv) C:\Users\niles\#OpenSource\tracardi-api>pip install -r app\\requirements.txt
Collecting git+https://github.com/Tracardi/tracardi.git@master (from -r app\\requirements.txt (line 14))
  Cloning https://github.com/Tracardi/tracardi.git (to revision master) to c:\users\niles\appdata\local\temp\pip-req-build-x1ze1oc2
  Running command git clone -q https://github.com/Tracardi/tracardi.git 'C:\Users\niles\AppData\Local\Temp\pip-req-build-x1ze1oc2'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\niles\#opensource\tracardi-api\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\niles\\AppData\
\Local\\Temp\\pip-req-build-x1ze1oc2\\setup.py'"'"'; __file__='"'"'C:\\Users\\niles\\AppData\\Local\\Temp\\pip-req-build-x1ze1oc2\\setup.py'"'"';f=getattr(tokenize
, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\niles\AppData\Local\Temp\pip-req-build-x1ze1oc2\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\niles\AppData\Local\Temp\pip-req-build-x1ze1oc2\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Users\niles\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 322: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 22.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


```
I also tried setting up development environment in wsl2 which gave the following error where I have Python3.8.10 version installed
```
(venv) omkhade@Om:~/OpenSource/tracardi$ pip install -r tracardi/requirements.txt
Collecting git+https://github.com/Tracardi/worker.git@master (from -r tracardi/requirements.txt (line 1))
  Cloning https://github.com/Tracardi/worker.git (to revision master) to /tmp/pip-req-build-pxm82626
  Running command git clone -q https://github.com/Tracardi/worker.git /tmp/pip-req-build-pxm82626
ERROR: Package 'worker' requires a different Python: 3.8.10 not in '>=3.9'
```
could you please help me resolve any one of the errors?

**Comment by atompie** [comment]
@khadeom You need to install python 3.9. Now tracardi need python 3.9.

```
Package 'worker' requires a different Python: 3.8.10 not in '>=3.9'
```

**Comment by atompie** [comment]
@khadeom Sorry for inconvenience. I did not notice that the docs say that you need python3.8 we recently changed it to python 3.9. I have already changed the docs to reflect this.

**Comment by khadeom** [comment]
Thanks @atompie i will proceed with python 3.9.

**Comment by khadeom** [comment]
Hi, I'm following the documentation to set up the developer Environment in windows.
I have Python-3.9.13 installed.
while following the steps mentioned in the docs im getting following error
```
(venv) C:\Users\niles\Tracardi\tracardi-api>pip install -r app\\requirements.txt
Collecting git+https://github.com/Tracardi/tracardi.git@master (from -r app\\requirements.txt (line 14))
  Cloning https://github.com/Tracardi/tracardi.git (to revision master) to c:\users\niles\appdata\local\temp\pip-req-build-ghjesnrj
  Running command git clone --filter=blob:none --quiet https://github.com/Tracardi/tracardi.git 'C:\Users\niles\AppData\Local\Temp\pip-req-build-ghjesnrj'
  Resolved https://github.com/Tracardi/tracardi.git to commit dfcc241f2d82e624727ce765575432372d2ef9c6
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\niles\AppData\Local\Temp\pip-req-build-ghjesnrj\setup.py", line 4, in <module>
          long_description = fh.read()
        File "C:\Users\niles\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 322: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```
I have followed all the steps mentioned in the docs multiple times still getting the error.

**Comment by atompie** [comment]
@riccardobucco Hello if you would like to take a look at this issue then it can be yours. It is very similar to this one.

**Comment by riccardobucco** [comment]
@atompie Sure, I will work on this, can you please assign it to me?

**Comment by atompie** [comment]
@riccardobucco Can you comment on this issue: https://github.com/Tracardi/tracardi/issues/742. So I can assign you
