### ISSUE TITLE
On heavy load - error

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#78]
This is due to the blocking nature of plugin: Agent detector

WARNING:elasticsearch:GET http://192.168.1.103:9200/tracardi-token/_doc/351f4dfa10076c561b743364b7ff939666633da4f9b4abfd913842efa5e67fb5 [status:N/A request:10.951s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/_async/http_aiohttp.py", line 291, in perform_request
    async with self.session.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None

**Comment by atompie** [comment]
Could not replicate
