### ISSUE TITLE
profile search error

### ISSUE THREAD

**Issue by MaratIR** [Tracardi/tracardi#846]
if you search for a profile by phone number, if there is no profile, there are no errors (screen 1). but if a profile is found, there is an error (screen 2). 

![image](https://github.com/Tracardi/tracardi/assets/61867280/ed4dcca4-659a-410e-81f6-3a78a1f5bcf0)
![image](https://github.com/Tracardi/tracardi/assets/61867280/65565953-845b-49d1-951f-fe5660da0deb)
```
1 validation error for Result value Input should be a valid dictionary [type=dict_type, input_value=Profile(id='d42d734d-3132...res=None, points=0.0)))), input_type=Profile] For further information visit https://errors.pydantic.dev/2.3/v/dict_type. Check run method of `InjectProfileByField` Details: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/tracardi/service/wf/domain/graph_invoker.py", line 332, in run_node result = await task File "/usr/local/lib/python3.10/site-packages/tracardi/service/wf/service/life_cycle/plugin.py", line 74, in execute return await node.object.run(**params) File "/usr/local/lib/python3.10/site-packages/tracardi/process_engine/action/v1/internal/inject_profile_by_field/plugin.py", line 58, in run return Result(port="profile", value=profile) File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 165, in __init__ __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__) pydantic_core._pydantic_core.ValidationError: 1 validation error for Result value Input should be a valid dictionary [type=dict_type, input_value=Profile(id='d42d734d-3132...res=None, points=0.0)))), input_type=Profile] For further information visit https://errors.pydantic.dev/2.3/v/dict_type
```

**Comment by atompie** [comment]
Error fixed. Fix incorporated into dockerhub version 0.8.2-rc2. Please pull new docker for the changes.
